# Make sure ocamlbuild can find opam-managed packages: first run
#
# eval `opam config env`

# Easiest way to build: using ocamlbuild, which in turn uses ocamlfind

.PHONY : DNAs.native

runDNAs.native :
	ocamlbuild -use-ocamlfind -pkgs llvm,llvm.analysis -cflags -w,+a-4 \
		DNAs.native

# "make clean" removes all generated files

.PHONY : clean
clean :
	ocamlbuild -clean
	rm -rf test_DNAs.log *.diff DNAs scanner.ml parser.ml parser.mli
	rm -rf *.cmx *.cmi *.cmo *.cmx *.o *.ll

# More detailed: build using ocamlc/ocamlopt + ocamlfind to locate LLVM

OBJS = ast.cmx codegen.cmx parser.cmx scanner.cmx semant.cmx DNAs.cmx

DNAs : $(OBJS)
	ocamlfind ocamlopt -linkpkg -package llvm -package llvm.analysis $(OBJS) -o DNAs

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

%.cmx : %.ml
	ocamlfind ocamlopt -c -package llvm $<

### Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
ast.cmo :
ast.cmx :
codegen.cmo : ast.cmo
codegen.cmx : ast.cmx
DNAs.cmo : semant.cmo scanner.cmo parser.cmi codegen.cmo ast.cmo
DNAs.cmx : semant.cmx scanner.cmx parser.cmx codegen.cmx ast.cmx
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmi
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
semant.cmo : ast.cmo
semant.cmx : ast.cmx
parser.cmi : ast.cmo

# Building the tarball

TESTS = hw hw2 hw3

FAILS = assign1

TESTFILES = $(TESTS:%=test-%.dnas) $(TESTS:%=test-%.out) \
	    $(FAILS:%=fail-%.dnas) $(FAILS:%=fail-%.err)

TARFILES = ast.ml codegen.ml Makefile DNAs.ml parser.mly README scanner.mll \
	semant.ml testall.sh $(TESTFILES:%=dna_tests/%)

DNAs-llvm.tar.gz : $(TARFILES)
	cd .. && tar czf DNAs-llvm/DNAs-llvm.tar.gz \
		$(TARFILES:%=DNAs-llvm/%)
