#!/bin/bash
# My first script

ocamllex scanner.mll

ocamlyacc parser.mly

ocamlc -c ast.mli # compile AST types

ocamlc -c parser.mli # compile parser types

ocamlc -c scanner.ml # compile the scanner

ocamlc -c parser.ml # compile the parser

ocamlc -c sampleprogram.ml # compile the interpreter

ocamlc -o calc parser.cmo scanner.cmo sampleprogram.cmo

./calc
